// _playgrounds/react/next/src/Modules/AtlasMissionsModule/AtlasMissionList.tsx
"use client";

import { AtlasMissionSearch } from "@lanka-playgrounds/react-shared/dom";
import { createAtlasMissionsVM, AtlasMissionGateway } from "@lanka-playgrounds/_shared";
import { formatAtlasMissionLine, useAtlasHydratedMissions } from "@lanka-playgrounds/react-shared";
import type { IAtlasMission } from "@lanka-playgrounds/_shared";
import type { JSX } from "react";

export interface IAtlasMissionListProps {
	/** What the server fetched, as an ordinary prop. */
	missions: readonly IAtlasMission[];
}

/**
 * The ViewModel, built once for this browser tab.
 *
 * At module level deliberately, and only in a CLIENT component: a ViewModel is a
 * store, so one module means one store per process — which in a browser is one
 * per tab and on a server would be one shared by every user connected to it.
 * That is the whole reason this file carries `"use client"`.
 */
const missionsVM = createAtlasMissionsVM(new AtlasMissionGateway());

/**
 * The board, starting from what the server already had.
 *
 * Three lines of this screen are the React ecosystem's and not Next's — the
 * hydrating read, the search box and the line format — so they live in
 * `@lanka-playgrounds/react-shared` and the Astro island imports the same three.
 * What is left here is the part that IS Next: `"use client"`, and a module-level
 * store that only a client bundle may hold.
 */
export const AtlasMissionList = ({ missions }: IAtlasMissionListProps): JSX.Element => {
	const { rows, applySearch, search } = useAtlasHydratedMissions(missionsVM, missions);

	return (
		<section aria-label="Missions">
			<AtlasMissionSearch search={search} onSearch={applySearch} />
			<ul>
				{rows().items.map((mission) => (
					<li key={mission.id}>{formatAtlasMissionLine(mission)}</li>
				))}
			</ul>
		</section>
	);
};

// _playgrounds/svelte/sveltekit/src/lib/Modules/AtlasMissionsModule/AtlasMissionList.svelte
<script lang="ts">
	import { AtlasMissionGateway, createAtlasMissionsVM } from "@lanka-playgrounds/_shared";
	import { formatAtlasMissionLine, useAtlasMissions } from "@lanka-playgrounds/svelte-shared";
	import { hydrateLankaVM } from "@lankajs/host";
	import type { IAtlasMission } from "@lanka-playgrounds/_shared";

	/**
	 * The board, starting from what the server already had.
	 *
	 * The handoff is DATA, not state: `+page.server.ts` fetched through a gateway
	 * inside a request scope, Kit carried the result to the browser in its
	 * serialised `data`, and `hydrateLankaVM` makes it this ViewModel's first
	 * state. There is no second request from the browser for what the HTML already
	 * contained.
	 *
	 * ## The ViewModel is per INSTANCE here, and in Nuxt it is per module
	 *
	 * That is not a preference, it is the two frameworks' own rule. Kit's docs say
	 * it outright: on the server, module-level state is shared by every user
	 * connected to that process, so a ViewModel declared beside this component
	 * would be one store for the whole deployment — and the first request to write
	 * a user's draft into it would serve that draft to the next stranger.
	 *
	 * `_playgrounds/vue/nuxt` had to go the other way, because Vue's
	 * `<script setup>` IS the `setup()` function and a module-level store was the
	 * only way to make hydration apply once. Here the instance script runs per
	 * render on the server AND per mount in the browser, which is exactly the
	 * lifetime a hydrated store wants: one store, one page, one reader.
	 *
	 * ## No `"use client"`, and nothing standing in for it
	 *
	 * That directive is React Server Components' mechanism and Kit has none: this
	 * component runs on both sides, and what keeps it correct is the lifetime
	 * above rather than a marker.
	 */
	const { missions }: { missions: readonly IAtlasMission[] } = $props();

	// svelte-ignore state_referenced_locally
	const missionsVM = createAtlasMissionsVM(new AtlasMissionGateway());

	// svelte-ignore state_referenced_locally
	hydrateLankaVM(missionsVM, { missions });

	const board = useAtlasMissions(missionsVM);
</script>

<section aria-label="Missions">
	<input
		aria-label="Search missions"
		value={board.search}
		oninput={(event) => board.applySearch((event.currentTarget as HTMLInputElement).value)}
	/>
	<ul>
		{#each board.rows().items as row (row.id)}
			<li>{formatAtlasMissionLine(row)}</li>
		{/each}
	</ul>
</section>
