// _playgrounds/solid/spa/src/Modules/AtlasMissionsModule/AtlasMissionsScreen.tsx
import { For, Show, onCleanup, onMount } from "solid-js";
import { formatAtlasMissionLine, useAtlasMissions } from "@lanka-playgrounds/solid-shared";
import type { TAtlasMissionsVM } from "@lanka-playgrounds/solid-shared";

/**
 * The board, and nothing else.
 *
 * It reads ONE view and owns nothing: no loading flag, no retry, no decision
 * about what a failure means. Every one of those belongs to the ViewModel — the
 * same sentence the React, Vue and Svelte screens carry, about the same
 * ViewModel, with only Solid's syntax between them.
 *
 * `onMount` rather than an effect: the fetch happens ONCE, when the screen
 * exists. In Solid the component body already runs once, so this is belt and
 * braces — but it is the same word the other three screens use, and a reader
 * moving between them should not have to notice.
 *
 * `<Show>` and `<For>` rather than `&&` and `.map()`, which is not decoration.
 * A Solid component runs once: a `.map()` in the body would iterate the list it
 * saw on that single run and never again, and the screen would be frozen with no
 * error anywhere. This is the one place where Solid's syntax is not a preference.
 */
export const AtlasMissionsScreen = (props: { missionsVM: TAtlasMissionsVM }) => {
	const missions = useAtlasMissions(props.missionsVM);

	onMount(() => {
		void missions().fetchMissions();
	});

	onCleanup(() => {
		missions.stop();
	});

	return (
		<section aria-label="Missions">
			<header>
				<input
					aria-label="Search missions"
					value={missions().search}
					onInput={(event) => missions().applySearch(event.currentTarget.value)}
				/>
				<button type="button" onClick={() => missions().sortBy("priority")}>
					Sort by priority
				</button>
			</header>

			<Show when={missions().error !== null}>
				<p role="alert">{missions().error}</p>
			</Show>
			<Show when={missions().isLoading}>
				<p role="status">Loading the board…</p>
			</Show>

			<ul>
				<For each={missions().rows().items}>
					{(row) => (
						<li>
							{formatAtlasMissionLine(row)}
							<button
								type="button"
								// `void`: the action returns a promise and a DOM handler has nowhere to put
								// one. The ViewModel already owns what a failure means, so there is
								// nothing here to await and nothing to catch.
								onClick={() => void missions().completeMission(row.id)}
							>
								Complete {row.code}
							</button>
						</li>
					)}
				</For>
			</ul>

			<footer>
				<button
					type="button"
					disabled={missions().page <= 1}
					onClick={() => missions().goToPage(missions().page - 1)}
				>
					Previous
				</button>
				<span data-testid="page">
					{missions().page} / {missions().rows().totalPages}
				</span>
				<button
					type="button"
					disabled={missions().page >= missions().rows().totalPages}
					onClick={() => missions().goToPage(missions().page + 1)}
				>
					Next
				</button>
			</footer>
		</section>
	);
};

// _playgrounds/angular/spa/src/Modules/AtlasMissionsModule/AtlasMissionsScreen.ts
import { ChangeDetectionStrategy, Component, OnInit, inject } from "@angular/core";
import {
	ATLAS_MISSIONS_VM,
	formatAtlasMissionLine,
	useAtlasMissions,
} from "@lanka-playgrounds/angular-shared";

/**
 * The board, and nothing else.
 *
 * It reads ONE view and owns nothing: no loading flag, no retry, no decision
 * about what a failure means. Every one of those belongs to the ViewModel — the
 * same sentence the React, Vue, Svelte and Solid screens carry, about the same
 * ViewModel, with only Angular's syntax between them.
 *
 * `ChangeDetectionStrategy.OnPush`, which under zoneless is not an optimisation
 * but the only strategy there is: what marks this view dirty is the signal the
 * binding writes, and nothing else ever will.
 *
 * `inject(ATLAS_MISSIONS_VM)` in a field initialiser rather than an `input`: a
 * ViewModel is a DEPENDENCY, not data a parent changes, and `useLankaVM` must
 * run in an injection context because `DestroyRef` is what ends its
 * subscription. `../../../_shared` states the case at length.
 */
@Component({
	selector: "atlas-missions-screen",
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<section aria-label="Missions">
			<header>
				<input
					aria-label="Search missions"
					[value]="missions().search"
					(input)="missions().applySearch($any($event.target).value)"
				/>
				<button type="button" (click)="missions().sortBy('priority')">
					Sort by priority
				</button>
			</header>

			@if (missions().error !== null) {
				<p role="alert">{{ missions().error }}</p>
			}
			@if (missions().isLoading) {
				<p role="status">Loading the board…</p>
			}

			<ul>
				@for (row of missions().rows().items; track row.id) {
					<li>
						{{ line(row) }}
						<button type="button" (click)="complete(row.id)">
							Complete {{ row.code }}
						</button>
					</li>
				}
			</ul>

			<footer>
				<button
					type="button"
					[disabled]="missions().page <= 1"
					(click)="missions().goToPage(missions().page - 1)"
				>
					Previous
				</button>
				<span data-testid="page"
					>{{ missions().page }} / {{ missions().rows().totalPages }}</span
				>
				<button
					type="button"
					[disabled]="missions().page >= missions().rows().totalPages"
					(click)="missions().goToPage(missions().page + 1)"
				>
					Next
				</button>
			</footer>
		</section>
	`,
})
export class AtlasMissionsScreen implements OnInit {
	readonly missions = useAtlasMissions(inject(ATLAS_MISSIONS_VM));

	readonly line = formatAtlasMissionLine;

	/**
	 * The fetch happens ONCE, when the screen exists.
	 *
	 * `ngOnInit` and not the field initialiser above: a constructor that starts a
	 * request makes the component impossible to construct without one, which is
	 * what every other screen in this folder avoids by using its framework's mount
	 * hook. `void` because the hook cannot await — the ViewModel already owns what
	 * a failure means.
	 */
	ngOnInit(): void {
		void this.missions().fetchMissions();
	}

	/**
	 * A method and not an inline expression, because the action returns a promise.
	 *
	 * A template expression has nowhere to put one, and the ViewModel already owns
	 * what a failure means — so there is nothing here to await and nothing to
	 * catch.
	 */
	complete(id: string): void {
		void this.missions().completeMission(id);
	}
}
