// modules/bindings/react/_playground/playground-todo-screen/PlaygroundTodoScreen.tsx
import { useLankaVM } from "../../src/index";
import type { ILankaFakeVMActions, ILankaFakeVMState } from "@lankajs/tool-testing";
import type { ILankaReadableVM } from "lanka/viewmodel";

/** What the screen needs: a ViewModel to read, and a way to observe its renders. */
export interface IPlaygroundTodoScreenProps {
	todosVM: ILankaReadableVM<ILankaFakeVMState & ILankaFakeVMActions>;
	onRender?: () => void;
}

/**
 * The screen. Reads state, calls actions, and decides nothing.
 *
 * It takes the ViewModel and reaches for it through `useLankaVM` ITSELF rather
 * than being handed a hook — which is what a consumer writes, and what makes the
 * same ViewModel readable from a Vue or Svelte screen without changing.
 *
 * Written in JSX rather than `createElement` because that is what a consumer
 * writes: a playground that avoids the consumer's syntax stops proving the
 * consumer's build works.
 */
export const PlaygroundTodoScreen = ({ todosVM, onRender }: IPlaygroundTodoScreenProps) => {
	const { rows, error, isLoading } = useLankaVM(todosVM);
	onRender?.();

	if (error !== null) return <p role="alert">{error}</p>;
	if (isLoading) return <p>loading</p>;

	return (
		<ul>
			{rows.map((row) => (
				<li key={row}>{row}</li>
			))}
		</ul>
	);
};

// modules/bindings/svelte/_playground/playground-todo-screen/PlaygroundTodoScreen.svelte
<script lang="ts">
	import { useLankaVM } from "../../src/index";
	import type { ILankaFakeVMActions, ILankaFakeVMState } from "@lankajs/tool-testing";
	import type { ILankaReadableVM } from "lanka/viewmodel";

	// The screen. Reads state, calls actions, and decides nothing.
	//
	// A real `.svelte` component, compiled by the plugin: what `renderWithLanka`
	// renders is a component, and proving the subpath with anything less would be
	// proving something else.
	const { todosVM }: { todosVM: ILankaReadableVM<ILankaFakeVMState & ILankaFakeVMActions> } =
		$props();

	const state = useLankaVM(todosVM);
</script>

{#if state.error !== null}
	<p role="alert">{state.error}</p>
{:else if state.isLoading}
	<p>loading</p>
{:else}
	<ul>
		{#each state.rows as row (row)}
			<li>{row}</li>
		{/each}
	</ul>
{/if}
