// _playgrounds/react/spa/src/main.tsx
import { createAtlasReleaseGuard } from "@lanka-playgrounds/_shared";
import { createAtlasAvatarCache } from "@lanka-playgrounds/_shared";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { renderLankaDevtoolsPanel } from "@lankajs/plugin-devtools";
import { setLankaStorageSecret } from "@lankajs/storage";
import { AtlasApp } from "./App/AtlasApp";
import { startAtlasBrowser } from "./startAtlasBrowser";

/**
 * The entry point: start, then render, and nothing else in the file.
 *
 * Every line here is ordered on purpose.
 *
 * `setLankaStorageSecret` comes FIRST, before anything can read or write: the
 * storage has no default secret and refuses loudly without one, because a
 * shipped fallback secret is the absence of encryption disguised as its
 * presence.
 *
 * The release guard runs before the first screen, and its answer is READ rather
 * than acted on. A reload would be the commonest response and the worst
 * default — somebody halfway through a dispatch would lose it — so this
 * application writes a line and moves on.
 *
 * `hydrate()` on the avatar cache is before the first render, or the first
 * render takes the network path and the cache appears not to work.
 */
const apiBaseUrl = import.meta.env.VITE_ATLAS_API ?? "http://127.0.0.1:4380/api";

setLankaStorageSecret(import.meta.env.VITE_ATLAS_SECRET ?? "atlas-playground-secret");

const guard = createAtlasReleaseGuard(apiBaseUrl, {
	report: (message) => console.info(message),
});
const released = await guard.check();

const avatars = createAtlasAvatarCache();
await avatars.hydrate();

const browser = await startAtlasBrowser({
	apiBaseUrl,
	isDevelopment: import.meta.env.DEV,
});

const root = document.getElementById("root");
if (root === null) throw new Error("Atlas has nowhere to render: #root is missing");

createRoot(root).render(
	<StrictMode>
		<AtlasApp browser={browser} avatars={avatars} />
	</StrictMode>,
);

console.info(`atlas started: release ${released}, avatars on ${avatars.getBackend()}`);

// In a production build this does nothing and returns before any work: a panel
// there is not a little extra code, it is an interface that can appear on
// somebody's screen.
renderLankaDevtoolsPanel(
	() =>
		(
			globalThis as { __atlas?: { getSnapshot: () => unknown } }
		).__atlas?.getSnapshot() as never,
	{},
);

// _playgrounds/solid/spa/src/index.tsx
import { setLankaStorageSecret } from "@lankajs/storage";
import { render } from "solid-js/web";
import { createAtlasAvatarCache } from "@lanka-playgrounds/_shared";
import { AtlasApp } from "./App/AtlasApp";
import { startAtlasSolid } from "./startAtlasSolid";

/*
 * The secret comes FIRST, before anything can read or write.
 *
 * `@lankajs/storage` has no default and refuses loudly without one, because a
 * shipped fallback secret is the absence of encryption disguised as its
 * presence. What it buys is worth saying plainly: it is baked into the build, so
 * it is obfuscation rather than protection against a script running on this page
 * — what it does is keep personal data out of `localStorage` as plain text.
 *
 * A real application reads this from its build and would never find it in source
 * control. These are demonstrations whose personal data is the string "Ada", and
 * the value below is named so that nobody mistakes it for a pattern to copy.
 */
setLankaStorageSecret("atlas-playground-not-a-real-secret");

/**
 * The executable entry, and the only file here that reads the environment.
 *
 * Three lines, like every other application's entry in this folder — which is
 * the point of them all being three lines: what differs between the hosts is
 * above this file, not in it.
 *
 * `hydrate()` on the avatar cache is awaited BEFORE the first render, for the
 * same reason the React entry states: `getInitialSrc` is synchronous and final,
 * so a render that beat the hydration takes the network path for every face and
 * the cache looks broken.
 */
const app = await startAtlasSolid({
	apiBaseUrl: import.meta.env.VITE_ATLAS_API ?? "http://127.0.0.1:4380/api",
	isDevelopment: import.meta.env.DEV,
});

const avatars = createAtlasAvatarCache();
await avatars.hydrate();

const root = document.getElementById("root");

if (root) render(() => <AtlasApp app={app} avatars={avatars} />, root);
